//types de agregar productos
export const AGREGAR_PRODUCTO = "AGREGAR_PRODUCTO";
export const AGREGAR_PRODUCTO_EXITO = "AGREGAR_PRODUCTO_EXITO";
export const AGREGAR_PRODUCTO_ERROR = "AGREGAR_PRODUCTO_ERROR";
//types de descarga de productos
export const COMENZAR_DESCARGA_PRODUCTOS = "COMENZAR_DESCARGA_PRODUCTOS";
export const DESCARGA_PRODUCTOS_EXITO = "DESCARGA_PRODUCTOS_EXITO";
export const DESCARGA_PRODUCTOS_ERROR = "DESCARGA_PRODUCTOS_ERROR";
//types de eliminar productos
export const OBTENER_PRODUCTO_ELIMINAR = "OBTENER_PRODUCTO_ELIMINAR";
export const PRODUCTO_ELIMINADO_EXITO = "PRODUCTO_ELIMINADO_EXITO";
export const PRODCUTO_ELIMINADO_ERROR = "PRODCUTO_ELIMINADO_ERROR";
//types de editar productos
export const OBTENER_PRODUCTO_EDITAR = "OBTENER_PRODUCTO_EDITAR";
export const PRODUCTO_EDITADO_EXITO = "PRODUCTO_EDITADO_EXITO";
export const PRODUCTO_EDITADO_ERROR = "PRODUCTO_EDITADO_ERROR";
//types de alertas
export const MOSTRAR_ALERTA = "MOSTRAR_ALERTA";
export const OCULTAR_ALERTA = "OCULTAR_ALERTA";
